### ISSUE TITLE
UI & Web service Integration

### ISSUE THREAD

**Issue by zerosign** [aqidd/ITW#2]
Some UI in Android (Titanium) are deprecated or even not compatible.

Problems :
1. TabGroup in Android Titanium need to be the root of activity and cannot be added into the current window.
2. Since there is point number 1, then TabbedBar need also to be reimplemented with simple toggle Button implementation alike.
3. Need to make the listview more 'inter-changeable' by implementing model-view-renderer alike in ListView. 
4. Need to implement own preference view in Titanium #sigh. Currently, there is no implementation exists there.
5. Need to implement & test better xhr implementation (Untested in zerosign-branch).

**Comment by aqidd** [comment]
for problem number 1 & 2, I guess you don't have to create the layout with tab group. you can replace the tab group with group of buttons with different actions dependent on the list view associated. how's that? XD

**Comment by zerosign** [comment]
Yup, that's what I'm trying to do with, right now.. I'm trying my best with the next commit in my branch :D

**Comment by zerosign** [comment]
And I think that what it means to be ''reimplementation' word comes from.

**Comment by aqidd** [comment]
haha. 'kay. good luck dude. anyway, can we meet tomorrow night after PKP? in the headquarter as usual.

**Comment by zerosign** [comment]
sorry the context in your last message not related directly to this issue. #hahahaha
_yup_
